apiVersion: v1
kind: Secret
metadata:
  name: "vc-config-{{ (include "vcluster.name" .) }}"
  namespace: {{ (include "vcluster.namespace" .) }}
  labels:
    app: vcluster
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ (include "vcluster.name" .) }}"
    heritage: "{{ .Release.Service }}"
  {{- if .Values.controlPlane.advanced.globalMetadata.annotations }}
  annotations:
{{ toYaml .Values.controlPlane.advanced.globalMetadata.annotations | indent 4 }}
  {{- end }}
type: Opaque
data:
  config.yaml: {{ .Values | toYaml | b64enc | quote }}
