{{- if .Values.policies.limitRange.enabled }}
apiVersion: v1
kind: LimitRange
metadata:
  name: vc-{{ (include "vcluster.name" .) }}
  {{- if .Values.experimental.syncSettings.targetNamespace }}
  namespace: {{ .Values.experimental.syncSettings.targetNamespace }}
  {{- else }}
  namespace: {{ (include "vcluster.namespace" .) }}
  {{- end }}
  labels:
    app: vcluster
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ (include "vcluster.name" .) }}"
    heritage: "{{ .Release.Service }}"
    {{- if .Values.policies.limitRange.labels }}
{{ toYaml .Values.policies.limitRange.labels | indent 4 }}
    {{- end }}
  {{- $annotations := merge dict .Values.controlPlane.advanced.globalMetadata.annotations .Values.policies.limitRange.annotations }}
  {{- if $annotations }}
  annotations:
{{ toYaml $annotations | indent 4 }}
  {{- end }}
spec:
  limits:
  - default:
      {{- range $key, $val := .Values.policies.limitRange.default }}
      {{ $key }}: {{ $val | quote }}
      {{- end }}
    defaultRequest:
      {{- range $key, $val := .Values.policies.limitRange.defaultRequest }}
      {{ $key }}: {{ $val | quote }}
      {{- end }}
    type: Container
{{- end }}
