{{- if .Values.rbac.role.enabled }}
{{- if .Values.experimental.multiNamespaceMode.enabled }}
kind: ClusterRoleBinding
{{- else -}}
kind: RoleBinding
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
{{- if .Values.experimental.multiNamespaceMode.enabled }}
  name: {{ template "vcluster.clusterRoleNameMultinamespace" . }}
{{- else }}
  name: vc-{{ (include "vcluster.name" .) }}
  namespace: {{ (include "vcluster.namespace" .) }}
{{- end }}
  labels:
    app: vcluster
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ (include "vcluster.name" .) }}"
    heritage: "{{ .Release.Service }}"
  {{- if .Values.controlPlane.advanced.globalMetadata.annotations }}
  annotations:
{{ toYaml .Values.controlPlane.advanced.globalMetadata.annotations | indent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    {{- if .Values.controlPlane.advanced.serviceAccount.name }}
    name: {{ .Values.controlPlane.advanced.serviceAccount.name }}
    {{- else }}
    name: vc-{{ (include "vcluster.name" .) }}
    {{- end }}
    namespace: {{ (include "vcluster.namespace" .) }}
roleRef:
{{- if .Values.experimental.multiNamespaceMode.enabled }}
  kind: ClusterRole
  name: {{ template "vcluster.clusterRoleNameMultinamespace" . }}
{{- else }}
  kind: Role
  name: vc-{{ (include "vcluster.name" .) }}
{{- end }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
